[project]
name = "workshop"
version = "0.1.0"
dependencies = [
  "pip>=24.1.1",
]
requires-python = ">=3.12"

[tool.rye]
virtual = true

[tool.rye.workspace]
members = ["exercises/*/*/sample", "exercises/*/*"]
